# Generated by Django 4.0.5 on 2022-06-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_rename_question_id_choice_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choice_id',
            new_name='choices',
        ),
    ]
