# Generated by Django 4.0.5 on 2022-06-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_choice_id_submission_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(to='onlinecourse.course'),
        ),
    ]
